name: Rust

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build all crates
        run: cargo build --verbose